### ISSUE TITLE
README sollte überarbeitet werden

### ISSUE THREAD

**Issue by madmartin** [vdr-projects/vdr-plugin-osdteletext#42]
Hi,

freut mich zu sehen daß wieder jemand weiter an vdr-plugins entwickelt!

Ich bin der Maintainer von
https://packages.gentoo.org/packages/media-plugins/vdr-osdteletext und
will mal anfragen wo die aktuellen Entwicklungsziele liegen?

An den letzten commits kann ich eine Version 2.0.0 erahnen? (hat sich erledigt, sie ist da...)

Würde mich freuen zu hören.

Übrigens: in der aktuellen README fehlt bei

Latest version available at:
https://github.com/vdr-projects/vdr-plugin-osdteletex  <<< ein T !!!

Grüsse aus Berlin

Martin

**Comment by pbiering** [comment]
typo gefixt, danke für's melden.

**Comment by madmartin** [comment]
Gern.
Da der Fix dann leider in version 2.0 nicht enthalten ist schlage ich vor Du löscht das release tag und setzt es nochmal auf den letzten commit. Normalerweise sollte man das nicht tun, aber da der Release ja erst ein paar Stunden her ist hat das garantiert ausser mir noch niemand bemerkt. Und ich würde bis zum Gentoo Paket Release 2.0.0 noch so lange warten.
CU
Mrtin

**Comment by pbiering** [comment]
tag verschoben auf den commit mit dem README Fix
