### ISSUE TITLE
2.2.0.beta.1 - farbtasten

### ISSUE THREAD

**Issue by butterweich** [vdr-projects/vdr-plugin-osdteletext#61]
hab hier folgendes problem:
farbtasten werden mit seitennummern belegt,
z.b. rot mit 100, gruen mit 200
klappt so weit auch, solange der vdr nicht beendet oder neu gestartet wird.

wird letzteres durchgefuehrt, sind die tasten allerdings nicht mehr belegt,
die korrekten parameter aber sind in der setup.conf eingetragen.
werden die evtl. bei einem neustart nicht korrekt initialisiert?

**Comment by pbiering** [comment]
Thank you for testing and reporting, fixed now (also one additional bug was solved).
